name: RangeBans
main: me.hqSparx.RangeBans.RangeBans
version: 1.01
description: Ban dynamic IP addresses
authors: [hqSparx]
commands:
  rb:
    description: Primary command for RangeBans.
    aliases: [rbans, rangeban, rangebans, rban]